/*
Segun [10] los tamaños son:
xs: 0B solo un get si  payload
S: 646B
M: 50kB
L: 500kB
*/

exports.DATA =
  "Nel mezzo del cammin di nostra vitami ritrovai per una selva oscura,ché la diritta via era smarrita.Ahi quanto a dir qual era è cosa duraesta selva selvaggia e aspra e forteche nel pensier rinova la paura!Tant' è amara che poco è più morte;ma per trattar del ben ch'i' vi trovai,dirò de l'altre cose ch'i' v'ho scorte.Io non so ben ridir com' i' v'intrai,tant' era pien di sonno a quel puntoche la verace via abbandonai.Ma poi ch'i' fui al piè d'un colle giunto,là dove terminava quella valleche m'avea di paura il cor compunto,guardai in alto e vidi le sue spallevestite già de' raggi del pianetache mena dritto altrui per ogne calle.Allor fo la paura un poco queta,che nel lago del cor m'era duratala notte ch'i' passai con tanta pieta.E come quei che con lena affannata,uscito fuor del pelago a la riva,si volge a l'acqua perigliosa e guata,così l'animo mio, ch'ancor fuggiva,si volse a retro a rimirar lo passoche non lasciò già mai persona viva.Poi ch'èi posato un poco il corpo lasso,ripresi via per la piaggia diserta,sì che 'l piè fermo sempre era 'l più basso.Ed ecco, quasi al cominciar de l'erta,una lonza leggera e presta molto,che di pel macolato era coverta;e non mi si partia dinanzi al volto,anzi 'mpediva tanto il mio cammino,ch'i' fui per ritornar più volte vòlto.Temp' era dal principio del mattino,e 'l sol montava 'n sù con quelle stellech'eran con lui quando l'amor divinomosse di prima quelle cose belle;sì ch'a bene sperar m'era cagionedi quella fiera a la gaetta pellel'ora del tempo e la dolce stagione;ma non sì che paura non mi dessela vista che m'apparve d'un leone.Questi parea che contra me venissecon la test' alta e con rabbiosa fame,sì che parea che l'aere ne tremesse.Ed una lupa, che di tutte bramesembiava carca ne la sua magrezza,e molte genti fé già viver grame,questa mi porse tanto di gravezzacon la paura ch'uscia di sua vista,ch'io perdei la speranza de l'altezza.E qual è quei che volontieri acquista,e giugne 'l tempo che perder lo face,che 'n tutti suoi ";
